[package]
name = "ccitt-group-4-tiff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

image = "0.24.7"
fax = "0.2.0"
tiff = "0.9.0"
